/**
 * Time Booking
 * Time Booking hooray!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type ErrorCodeEnum = "EXISTING_PROJECT_BOOKINGS" | "OVERLAPPING_TIME" | "TIME_OUT_OF_BOUNDS" | "TIME_LIMIT_EXCEEDED" | "ILLEGAL_TIME_BOUNDS" | "UNBOOKED_TIME" | "OPERATION_NOT_PERMITTED" | "ILLEGAL_DATE" | "VALIDATION_ERROR" | "EXISTING_VACATION" | "EXISTING_SICK_LEAVE" | "EXISTING_TIME_BOOKING_ENTRIES" | "USER_LOCKED" | "BOSS_LOCKED" | "PROJECT_NOT_FOUND" ;
