/**
 * Time Booking
 * Time Booking hooray!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeSpanWithID } from './TimeSpanWithID';
import { HttpFile } from '../http/http';

export class GETTimeBookingResponse {
    'timeSpans'?: Array<TimeSpanWithID>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timeSpans",
            "baseName": "timeSpans",
            "type": "Array<TimeSpanWithID>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GETTimeBookingResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

