/**
 * Time Booking
 * Time Booking hooray!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimePeriod } from './TimePeriod';
import { HttpFile } from '../http/http';

export class NotBookedTimePeriod {
    'date': string;
    'timePeriods': Array<TimePeriod>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "timePeriods",
            "baseName": "timePeriods",
            "type": "Array<TimePeriod>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NotBookedTimePeriod.attributeTypeMap;
    }
    
    public constructor() {
    }
}

