/**
 * Time Booking
 * Time Booking hooray!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProjectNameIDMap {
    'projectId'?: number;
    'projectName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "projectName",
            "baseName": "projectName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProjectNameIDMap.attributeTypeMap;
    }
    
    public constructor() {
    }
}

