/**
 * Time Booking
 * Time Booking hooray!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectTimeSpan } from './ProjectTimeSpan';
import { HttpFile } from '../http/http';

export class ProjectDateTimeSpans {
    'date': string;
    'project': number;
    'timeSpans': Array<ProjectTimeSpan>;
    'userlock'?: boolean;
    'bosslock'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "timeSpans",
            "baseName": "timeSpans",
            "type": "Array<ProjectTimeSpan>",
            "format": ""
        },
        {
            "name": "userlock",
            "baseName": "userlock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "bosslock",
            "baseName": "bosslock",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProjectDateTimeSpans.attributeTypeMap;
    }
    
    public constructor() {
    }
}

