/**
 * Time Booking
 * Time Booking hooray!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeSpanTypeEnum } from './TimeSpanTypeEnum';
import { HttpFile } from '../http/http';

export class TimeSpanWithoutID {
    'date': string;
    'type': TimeSpanTypeEnum;
    /**
    * Time Format in a 00:00 - 23:45 range, in 15 min units
    */
    'to'?: string;
    /**
    * Time Format in a 00:00 - 23:45 range, in 15 min units
    */
    'from'?: string;
    'homeoffice': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TimeSpanTypeEnum",
            "format": ""
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string",
            "format": ""
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "string",
            "format": ""
        },
        {
            "name": "homeoffice",
            "baseName": "homeoffice",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimeSpanWithoutID.attributeTypeMap;
    }
    
    public constructor() {
    }
}

