/**
 * Time Booking
 * Time Booking hooray!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorCodeEnum } from './ErrorCodeEnum';
import { HttpFile } from '../http/http';

export class TimeBookingError {
    'message'?: string;
    'code': ErrorCodeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "ErrorCodeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimeBookingError.attributeTypeMap;
    }
    
    public constructor() {
    }
}

