/**
 * Time Booking
 * Time Booking hooray!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeSpanTypeEnum } from './TimeSpanTypeEnum';
import { TimeSpanWithIDAllOf } from './TimeSpanWithIDAllOf';
import { TimeSpanWithoutID } from './TimeSpanWithoutID';
import { HttpFile } from '../http/http';

export class TimeSpanWithID {
    'userlock'?: boolean;
    'bosslock'?: boolean;
    'id': number;
    'date': string;
    'type': TimeSpanTypeEnum;
    /**
    * Time Format in a 00:00 - 23:45 range, in 15 min units
    */
    'to'?: string;
    /**
    * Time Format in a 00:00 - 23:45 range, in 15 min units
    */
    'from'?: string;
    'homeoffice': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userlock",
            "baseName": "userlock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "bosslock",
            "baseName": "bosslock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TimeSpanTypeEnum",
            "format": ""
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string",
            "format": ""
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "string",
            "format": ""
        },
        {
            "name": "homeoffice",
            "baseName": "homeoffice",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimeSpanWithID.attributeTypeMap;
    }
    
    public constructor() {
    }
}

