/**
 * Time Booking
 * Time Booking hooray!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type TimeSpanTypeEnum = "WORK" | "FULL_DAY_VACATION" | "HALF_DAY_VACATION" | "SICK_LEAVE" | "BREAK" ;
