/**
 * Time Booking
 * Time Booking hooray!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TimeBookingLockDate {
    'userlock': boolean;
    'bosslock': boolean;
    'date': string;
    'employee': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userlock",
            "baseName": "userlock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "bosslock",
            "baseName": "bosslock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "employee",
            "baseName": "employee",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return TimeBookingLockDate.attributeTypeMap;
    }
    
    public constructor() {
    }
}

