name: Pages

on:
  push:
    branches: [master]

jobs:
  publish-gh:
    name: Publish Github Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: npm install
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/apps/work-tracker
  notify-discord:
    name: Discord notification
    runs-on: ubuntu-latest
    needs: publish-gh
    steps:
      - uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
